### ISSUE TITLE
Calling a Transformation on a subroutine automatically applies itself recursively on contained subroutines.

### ISSUE THREAD

**Issue by JoeffreyLegaux** [ecmwf-ifs/loki#131]
Whenever a Transformation is applied to a routine object, the transformation is also implicitely applied to all its contained subroutines.
This behaviour is not controllable, and happens whether the contained subroutines are effectively called or not.

Applying this script :
[contained.py.txt](https://github.com/ecmwf-ifs/loki/files/12440361/contained.py.txt)

```
from loki import Frontend, Sourcefile, Transformation

class TestTransfo(Transformation):
    def transform_subroutine(self, routine, **kwargs):
    	print(f'Routine treated by transformation : {routine}')

source = Sourcefile.from_file('./routine.f90', frontend=Frontend.FP)

routines = source.subroutines

for routine in routines:
	print(f'Treating routine {routine}')
	routine.apply(TestTransfo())
```

To this routine :
[routine.f90.txt](https://github.com/ecmwf-ifs/loki/files/12440359/routine.f90.txt)

```
SUBROUTINE MY_ROUTINE()

WRITE(*,*) "Main subroutine"

! CALL MY_CONTAINED_ROUTINE()

CONTAINS 

SUBROUTINE MY_CONTAINED_ROUTINE()

  WRITE(*,*) "Contained subroutine"

END SUBROUTINE MY_CONTAINED_ROUTINE

END SUBROUTINE MY_ROUTINE
```

Produces in the console output :
```
Treating routine Subroutine:: MY_ROUTINE
Routine treated by transformation : Subroutine:: MY_ROUTINE
Routine treated by transformation : Subroutine:: MY_CONTAINED_ROUTINE
```

**Comment by reuterbal** [comment]
Thanks @JoeffreyLegaux for reporting this. I can confirm that this was intentional behaviour at the time but is indeed not a good design decision. Unfortunately, it is not trivial to remove it ad hoc because the current Scheduler implementation relies on that behaviour to apply transformations. Once the ongoing Scheduler rewrite is completed, this shouldn't be an issue anymore but I appreciate that that's taking too long.

However, I'm testing a possible implementation that would allow making that behaviour configurable already now - but I will have to discuss with other developers whether this is acceptable.

Importantly, this recursion behaviour is _not_ an issue if you apply transformations using the Scheduler - because that skips gracefully over subroutines that do not correspond to the currently processed item: https://github.com/ecmwf-ifs/loki/blob/3846c6776b7b6a6babe8753e20f7baa2bd476dac/loki/transform/transformation.py#L168

For bulk-transforming larger source trees, the use of the Scheduler is the recommended process but I'm assuming you are not currently using that?

**Comment by JoeffreyLegaux** [comment]
> For bulk-transforming larger source trees, the use of the Scheduler is the recommended process but I'm assuming you are not currently using that?

Yes, we are currently heading towards a file by file approach for the tansformation process at MF. 
This is not a critical issue since it can be worked around by moving routine.contains to a temporary object before applying the transformation.
