### ISSUE TITLE
issue with acc private 

### ISSUE THREAD

**Issue by ecossevin** [ecmwf-ifs/loki#224]
```
SUBROUTINE TOTO(A,B)

IMPLICIT NONE
REAL, INTENT(IN) :: A
REAL, INTENT(INOUT) :: B

!&ACC LOOP VECTOR &
!$ACC&PRIVATE( JBLK, JLON, YLCPG_BNDS, YLSTACK )


END SUBROUTINE TOTO

```

```
from loki import *
path="sub.F90"
file=Sourcefile.from_file(path)
routine=file["TOTO"]
print(fgen(routine))

```

The result of the fgen is `!$ACC PRIVATE( JBLK, JLON, YLCPG_BNDS, YLSTACK )` instead of `!$ACC&PRIVATE( JBLK, JLON, YLCPG_BNDS, YLSTACK )`

**Comment by mlange05** [comment]
Hi @ecossevin I'm not quite sure what to make of this example: On first inspection this looks like a typo, as the first of the two lines is not actually a pragma, but merely a comment. If you change `!&ACC LOOP VECTOR` to `!$ACC LOOP VECTOR` the regular behaviour for multi-line pragmas kicks in and the expected behaviour returns (I think). 
Is this what you were aiming for, or is this example meant to highlight that the line `!$ACC&PRIVATE ...` gets slightly changed in a parse-unparse cycle due to our pragma-detection (in which case I'd need to check if it is even valid syntax to use `!$ACC&` without a preceding pragma-line).
